# Generated by Django 3.2 on 2025-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0003_auto_20250305_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
