# Generated by Django 4.2.19 on 2025-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0005_chatmessage_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
